### ISSUE TITLE
In NtUtils.Processes.Create.Win32.pas, "if (Attributes.Mitigations <> 0) or (Attributes.Mitigations <> 0) then"

### ISSUE THREAD

**Issue by SolsticeProjekt** [diversenok/NtUtilsLibrary#2]
if (Attributes.Mitigations <> 0) or (Attributes.Mitigations <> 0) then

Based on the code, should the latter be Mitigations2 ?

**Comment by diversenok** [comment]
That's a good point, thanks. I cannot believe someone is actually reading the code, considering that I keep waiting to document it =)

**Comment by SolsticeProjekt** [comment]
Not sure you want to know, but ... I've read through a lot of it.
It's not fully supported by Free Pascal and I had to compile the latest trunk, but that's not enough.

I've spent a whole hour trying to get your code to run with free pascal lol ... but it didn't work out.

I am - at this point - desperately looking for a way to run child processes as low box app containers.
I've tried on my own, but createprocess always ends with error 87.

I've found your "Restart as App Container" function and hoped I could get this to run,
but nothing happens.

Would you be willing to help me?

**Comment by SolsticeProjekt** [comment]
Nevermind! Finally figured it out!
I've accidentially passed the address of the pointer to the startupinfo, instead of the pointer.

Sorry, but thanks anyway! : D
