### ISSUE TITLE
REQ: wscapi support

### ISSUE THREAD

**Issue by chmichael** [diversenok/NtUtilsLibrary#3]
Hello!
  Any chance to add support for wscapi  api ?

Thank you

**Comment by diversenok** [comment]
Hi. The Windows Security Center API seems to be a bit out of the scope of the project for several reasons:
 - It is a quite high-level abstraction
 - It is an antimalware-related API, and I do not want this projects to do anything directly related to this topic
 - I expect that linking to these functions would cause more false-positives from AVs

However, if you just want the translated version of wscapi.h, [you can have one](https://gist.github.com/diversenok/fada5c5f974ca95c5e5581009b32b1e7).

**Comment by chmichael** [comment]
Ok! Thank you very much for the unit and the NtUtilsLibrary! It's awesome!
