### ISSUE TITLE
Delphi 7

### ISSUE THREAD

**Issue by XUnderShadow** [diversenok/NtUtilsLibrary#5]
Can this work on Delphi 7?

**Comment by diversenok** [comment]
The main functionality - definitely no; it uses lots of features that appeared later (generics, anonymous functions, RTTI, etc.). It should be possible to reuse most of the definitions from the headers by removing all custom attributes and a few other things; however, the rest of the library relies too heavily on generic interfaces (which power automatic memory management for it).

Alternatively, you can get a free Community Edition of Delphi 10.4 that includes all these features here: https://www.embarcadero.com/products/delphi/starter

**Comment by XUnderShadow** [comment]
ok
Thanks
